export enum EProductRestrictions {
  NAME_MIN_LENGTH = 3,
  NAME_MAX_LENGTH = 100,
  DESCRIPTION_MIN_LENGTH = 5,
  DESCRIPTION_MAX_LENGTH = 500,
  PRICE_MIN = 0.1,
  PRICE_MAX = 100000,
  DISCOUNT_MAX = 99,
  DISCOUNT_MIN = 1,
  MIN_COUNT_TO_ORDER_MIN = 1,
  MIN_COUNT_TO_ORDER_MAX = 1000,
  MIN_QUANTITY = 1,
  MAX_QUANTITY = 10000,
}
